import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sketchesPath = resolve(__dirname, '../data/sketches.json');
const outPath = resolve(__dirname, '../src/config.js');

const json = JSON.parse(await readFile(sketchesPath, 'utf-8'));

const contents = `// Auto-generated by scripts/generate-config.mjs
export const sketches = ${JSON.stringify(json, null, 2)};
export default sketches;
`;

await writeFile(outPath, contents, 'utf-8');
console.log('Generated src/config.js');