import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sketchesPath = resolve(__dirname, "../data/sketches.json");
const outPath = resolve(__dirname, "../src/config.js");

const raw = JSON.parse(await readFile(sketchesPath, "utf-8"));
const sketches = Array.isArray(raw) ? raw : Array.isArray(raw?.sketches) ? raw.sketches : [];

const slugify = (str) =>
    String(str ?? "")
        .toLowerCase()
        .normalize("NFKD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || null;

const normalized = sketches.map((s, i) => {
    const base = s.slug ?? s.id ?? s.title ?? `sketch-${i + 1}`;
    const slug = slugify(base) ?? `sketch-${i + 1}`;
    return { ...s, slug };
});

const contents = `// Auto-generated by scripts/generate-config.mjs
export const sketches = ${JSON.stringify(normalized, null, 2)};
const config = { sketches };
export default config;
`;

await writeFile(outPath, contents, "utf-8");
console.log(`Generated src/config.js with ${normalized.length} sketches`);
