import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sketchesPath = resolve(__dirname, "../data/sketches.json");
const foldersPath = resolve(__dirname, "../data/folders.json");
const outPath = resolve(__dirname, "../src/config.js");

const raw = JSON.parse(await readFile(sketchesPath, "utf-8"));
const sketches = Array.isArray(raw) ? raw : Array.isArray(raw?.sketches) ? raw.sketches : [];

// Load folders
let folders = [];
if (existsSync(foldersPath)) {
    const foldersRaw = JSON.parse(await readFile(foldersPath, "utf-8"));
    folders = Array.isArray(foldersRaw) ? foldersRaw : [];
}

// Helper functions (same as server.js)
function normalizeAscii(str) {
    return str
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[İ]/g, "I")
        .replace(/[ı]/g, "i");
}

function generateSlug(title, author) {
    const lastName = normalizeAscii(author).trim().split(" ").pop().toLowerCase();
    const titleSlug = normalizeAscii(title)
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-+|-+$/g, "");
    return `${titleSlug}-${lastName}`;
}

const normalized = sketches.map((s) => ({
    ...s,
    slug: generateSlug(s.title, s.author),
}));

const contents = `// Auto-generated by scripts/generate-config.mjs
// Helper function to generate URL-friendly slugs from titles and author
function normalizeAscii(str) {
    return str
        .normalize("NFD")
        .replace(/[\\u0300-\\u036f]/g, "")
        .replace(/[İ]/g, "I")
        .replace(/[ı]/g, "i");
}

function generateSlug(title, author) {
    const lastName = normalizeAscii(author).trim().split(" ").pop().toLowerCase();
    const titleSlug = normalizeAscii(title)
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9\\s-]/g, "")
        .replace(/\\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-+|-+$/g, "");
    return \`\${titleSlug}-\${lastName}\`;
}

export const folders = ${JSON.stringify(folders, null, 2)};

export const sketchesData = ${JSON.stringify(normalized, null, 2)};

const Config = {
    folders,
    sketches: sketchesData.map((sketch) => ({
        ...sketch,
        slug: generateSlug(sketch.title, sketch.author),
    })),
};

export default Config;
`;

await writeFile(outPath, contents, "utf-8");
console.log(`Generated src/config.js with ${normalized.length} sketches and ${folders.length} folders`);
