// Auto-generated by scripts/generate-config.mjs
export const sketches = [
  {
    "author": "Elif Erpulat",
    "title": "Frog",
    "description": "Week 1 abstraction assignment in p5.js",
    "url": "https://openprocessing.org/sketch/2376645/embed",
    "width": 600,
    "height": 600,
    "slug": "frog"
  },
  {
    "author": "Ada Tıngaz",
    "title": "Checkered Paprika",
    "description": "",
    "url": "https://editor.p5js.org/ada.tingaz/full/I2N_Nwb6W",
    "width": 1080,
    "height": 1080,
    "slug": "checkered-paprika"
  },
  {
    "author": "Aslı Özcan",
    "title": "Turtle",
    "description": "",
    "url": "https://editor.p5js.org/asli.ozcan/full/ufM-LQ5Bj",
    "width": 1080,
    "height": 1080,
    "slug": "turtle"
  },
  {
    "author": "Baran Bülbül",
    "title": "week2 abstraction",
    "description": "",
    "url": "https://editor.p5js.org/Barannn/full/Pg8FhUxqo",
    "width": 1020,
    "height": 1020,
    "slug": "week2-abstraction"
  },
  {
    "author": "Buse Özdemir",
    "title": "week2 assignment",
    "description": "",
    "url": "https://editor.p5js.org/buse.ozdemir.33629/full/QETp7SwF8",
    "width": 1080,
    "height": 1080,
    "slug": "week2-assignment"
  },
  {
    "author": "Ceran Erdi",
    "title": "Flower",
    "description": "",
    "url": "https://editor.p5js.org/ceran/full/QYY3TZuHI",
    "width": 1080,
    "height": 1080,
    "slug": "flower"
  },
  {
    "author": "Deniz Mutlu",
    "title": "Crub",
    "description": "",
    "url": "https://editor.p5js.org/denizmutlu/full/NBXsFJiWo",
    "width": 1080,
    "height": 1080,
    "slug": "crub"
  },
  {
    "author": "Ece Matlı",
    "title": "week2",
    "description": "",
    "url": "https://editor.p5js.org/ecematli/full/tGdd9MIjX",
    "width": 800,
    "height": 800,
    "slug": "week2"
  },
  {
    "author": "Eda Erginoğlu",
    "title": "week2 abstraction",
    "description": "",
    "url": "https://editor.p5js.org/eda.erginoglu/full/mVAlnLvO9",
    "width": 1080,
    "height": 1080,
    "slug": "week2-abstraction"
  },
  {
    "author": "Farida Hamed",
    "title": "Candle",
    "description": "",
    "url": "https://editor.p5js.org/faridahamed/full/ktnaeAcUi",
    "width": 1080,
    "height": 1080,
    "slug": "candle"
  },
  {
    "author": "Ilgınsu Gündüzalp",
    "title": "Week2 abstraction assignment",
    "description": "",
    "url": "https://editor.p5js.org/ilginsugunduzalp/full/r5TvD1qGX",
    "width": 1080,
    "height": 1080,
    "slug": "week2-abstraction-assignment"
  },
  {
    "author": "Imran Nawaz",
    "title": "Glaze Resonance",
    "description": "",
    "url": "https://editor.p5js.org/iman.nawaz/full/l4BQ3QhMe",
    "width": 1080,
    "height": 1080,
    "slug": "glaze-resonance"
  },
  {
    "author": "Münazza Şirin",
    "title": "Cat",
    "description": "",
    "url": "https://editor.p5js.org/munazza.shirin/full/y-8_bApaH",
    "width": 1080,
    "height": 1080,
    "slug": "cat"
  },
  {
    "author": "Nehir Gelişin",
    "title": "Composition",
    "description": "",
    "url": "https://editor.p5js.org/nehir.gelisin/full/up-mE5cH9",
    "width": 1080,
    "height": 1080,
    "slug": "composition"
  },
  {
    "author": "Umut Gelir",
    "title": "Fish",
    "description": "",
    "url": "https://editor.p5js.org/tumurileg/full/yPM3SvNLr",
    "width": 1080,
    "height": 1080,
    "slug": "fish"
  },
  {
    "author": "Azra Akoğlu",
    "title": "Grapes",
    "description": "",
    "url": "https://editor.p5js.org/azra.akoglu/full/alZHFy1wQ",
    "width": 1080,
    "height": 1080,
    "slug": "grapes"
  },
  {
    "author": "Baran Ay",
    "title": "The Sun",
    "description": "",
    "url": "https://editor.p5js.org/baranay/full/THn3NDgr7",
    "width": 1080,
    "height": 1080,
    "slug": "the-sun"
  },
  {
    "author": "Bersu Güzey",
    "title": "Lamp",
    "description": "",
    "url": "https://editor.p5js.org/bersuguzey/full/Ifo7i0nfD",
    "width": 900,
    "height": 900,
    "slug": "lamp"
  },
  {
    "author": "Bilal Mushtaque",
    "title": "Abstract Fighter",
    "description": "",
    "url": "https://editor.p5js.org/bilal.mushtaque/full/jDgan7Pm7",
    "width": 1080,
    "height": 1080,
    "slug": "abstract-fighter"
  },
  {
    "author": "Cemre Toraman",
    "title": "Week2 Assignment",
    "description": "",
    "url": "https://editor.p5js.org/cemre.toraman/full/h5jcr5gUb",
    "width": 1080,
    "height": 1080,
    "slug": "week2-assignment"
  },
  {
    "author": "Ece Usta",
    "title": "Pokeball",
    "description": "",
    "url": "https://editor.p5js.org/ece.usta/full/TkzWzJ_EO",
    "width": 1080,
    "height": 1080,
    "slug": "pokeball"
  },
  {
    "author": "Mert Cambol",
    "title": "Portrait",
    "description": "",
    "url": "https://editor.p5js.org/mertcambol/full/d7Ya8w1g8",
    "width": 1080,
    "height": 1080,
    "slug": "portrait"
  },
  {
    "author": "Nur Akçay",
    "title": "Robot",
    "description": "",
    "url": "https://editor.p5js.org/meleknurakcay/full/z6m53tSqA",
    "width": 450,
    "height": 450,
    "slug": "robot"
  },
  {
    "author": "Nurdan Çelik",
    "title": "Mickey",
    "description": "",
    "url": "https://editor.p5js.org/nurdancelik90/full/hxnUkIrZV",
    "width": 1080,
    "height": 1080,
    "slug": "mickey"
  }
];
const config = { sketches };
export default config;
